SemestrWork1/SemestrWork1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("funCinema.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SemestrWork1/funCinema/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    path("serials_list/", views.SerialsView.as_view(), name='serials_list'),
    path('list/', views.add_list, name='list'),
    path('form/', views.serials_form, name='insert'),
    path('form/<int:id>/', views.serials_form, name='update'),
    path('delete/<int:id>/', views.delete_list, name='delete'),
    path("single_serial/", views.SerialDetailView.as_view(), name='single_serial'),
    path("<int:id>/", views.SingleSerial.as_view(), name='detail_serial'),
    path("actor/<int:id>/", views.ActorView.as_view(), name='actor_detail'),
    path('register/', views.register, name='register'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login')
]

SemestrWork1/funCinema/models.py
from django.db import models
from audioop import reverse

from django.db import models


class Category(models.Model):
    name = models.CharField("Категория", max_length= 100)
    description = models.TextField("Описание", max_length=500)
    url = models.SlugField(unique=False)

    def __str__(self):
        return self.name


class Actor(models.Model):
    FIO = models.CharField('ФИО', max_length= 100)
    age = models.IntegerField(default=0)
    description = models.TextField('Описание', max_length=500)
    image = models.ImageField(upload_to='actors/')

    def __str__(self):
        return self.FIO


class Genre(models.Model):
    name = models.CharField(max_length=100)
    url = models.SlugField(unique=False)

    def __str__(self):
        return self.name


class Serials(models.Model):
    title = models.CharField('Название',max_length=100)
    description = models.CharField('Описание', max_length= 200)
    poster = models.ImageField('Постер', upload_to='serials/')
    date = models.DateField('Дата выхода', null=True)
    country = models.CharField('Страна',max_length=100)
    actors = models.ManyToManyField(Actor, verbose_name='актеры', related_name='actor')   # использование M2M
    # related name позволяет запрашивать связанные сущности из бд
    genre = models.ManyToManyField(Genre, verbose_name='жанры')  # использование M2M
    category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.SET_NULL, null=True)    # использование O2M
    #если удалим категорию, то поле = 0
    url = models.SlugField(unique=False)
    link = models.URLField(max_length=200, blank=True)

    def __str__(self):   # возвращает удобочитаемую строку для названия
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = 'Сериал'
        verbose_name_plural = 'Сериалы'

class Cadrs(models.Model):
    name = models.CharField('Заголовок', max_length= 100)
    image = models.ImageField()
    serial = models.ForeignKey(Serials, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

SemestrWork1/funCinema/forms.py
from django import forms
from .models import Serials
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class Form(forms.ModelForm):
    class Meta:
        model = Serials
        fields = ('title', 'link')
        labels = {
            'title': 'Название',
            'link': 'Ссылка'
        }

    def __int__(self, *args, **kwargs):
        super(Form, self).__init__(*args, **kwargs)


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

SemestrWork1/funCinema/views.py
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Actor
from .models import Serials
from .forms import Form, UserRegisterForm



class SerialsView(View):
    def get(self, request):
        serials = Serials.objects.all()
        return render(request, "serials/serials_list.html", {"serials": serials})


class SerialDetailView(View):
    def get(self, request):
        serials = Serials.objects.all()
        return render(request, "serials/single_serial.html", {"serials": serials})


class SingleSerial(View):
    def get(self, request, id):
        serial = get_object_or_404(Serials, id=id)
        return render(request, "serials/detail_serial.html", {"serial": serial})


class ActorView(View):
    def get(self, request, id):
        serial = get_object_or_404(Actor, id=id)
        return render(request, "serials/actor.html", {"serial": serial})


def add_list(request):
    context = {'list': Serials.objects.all()}
    return render(request, 'serials/mySerial.html', context)



def serials_form(request):
    if request.method == "GET":
        form = Form()
        return render(request, 'serials/serials_form.html', {'form': form})
    else:
        form = Form(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/list/')


def delete_list(request):
    return


def serials_form(request, id=0):
    if request.method == "GET":
        if id == 0:
            form = Form()
        else:
            serials = Serials.objects.get(pk=id)
            form = Form(instance=serials)
        return render(request, 'serials/serials_form.html', {'form': form})
    else:
        if id == 0:
            form = Form(request.POST)
        else:
            serials = Serials.objects.get(pk=id)
            form = Form(request.POST, instance=serials)
        if form.is_valid():
            form.save()
        return redirect('/list/')


def delete_list(request, id):
    serials = Serials.objects.get(pk=id)
    serials.delete()
    return redirect('/list/')


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('serials_list')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

SemestrWork1/funCinema/templates/serials/actor.html
<!DOCTYPE html>
{% extends 'serials/base.html' %}
{% load static %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Сериалы</title>
    <link rel="stylesheet" href="{% static 'css/actor.css' %}">
</head>

<div class="container">
        <div class="item">
            <div class="image">
                <img src="{{ serial.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="items">
                <ul>
                    <b>Актер:</b> {{ serial.FIO }}
                    <p></p>
                    <b>Возраст:</b> {{ serial.age }} лет
                </ul>
            </div>
        </div>
        <div class="info">
            <h3 class="shop-sing editContent">
                О {{ serial.FIO }}
            </h3>
            <p class="ds">
                <a> {{ serial.description|safe }}</a>
            </p>
        </div>
    </div>
{% endblock %}

SemestrWork1/funCinema/templates/serials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div class = "box-area">
        <header>
            <div class="wrapper">
                <div class="logo">
                    <a href="#">Fun Cinema</a>
                    <a style="inset-inline: auto">{{ user.username }}</a>
                </div>
                <nav>
                    <a button type="submit" id="submit" onclick="alerted();">
                        Правила пользования</a>
                    <a href="{% url 'serials_list' %}">Главная</a>
                    <a href="{% url 'single_serial' %}">Сериалы</a>
                    <a href="{% url 'list' %}">Мои cериалы</a>
                    <a href="{% url 'login' %}">Выйти</a>
                </nav>
            </div>
        </header>
    </div>
{% block content %}
{% endblock %}
</body>
</html>

SemestrWork1/funCinema/templates/serials/base_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Мои любимые сериалы</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
</head>

<body>

    <div class="container">
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="jumbotron">
                <h1 class="display-4">Мои любимые сериалы</h1>
                <p class="lead font-italic">Сохраните ваши любимые сериалы, которые хотите посмотреть</p>
                <hr class="my-4">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

SemestrWork1/funCinema/templates/serials/detail_serial.html
<!DOCTYPE html>
{% extends 'serials/base.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/page.css' %}">
    <script src={% static "js/script.js" %}></script>
</head>
<body>
        <div class="container">
                    <div class="item">
                        <div class="posters">
                            <img src="{{ serial.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="titles">
                            <h1>
                                {{ serial.title }}
                            </h1>
                        <div class = "items">
                            <ul>
                                <li>
                                    <span><b>Дата:</b> {{ serial.date }}</span></li>
                                <li>
                                    <span><b>Страна:</b> {{ serial.country }}</span></li>

                                <li ><span><b>Актеры: </b>
                                    {% for actor in serial.actors.all %}
                                        <p>
                                            <a href="{% url 'actor_detail' actor.id %}">{{ actor }}</a>
                                        </p>
                                    {% endfor %}
                                </span>
                                </li>
                                <li ><span><b>Жанр: </b>
                                    {% for genre in serial.genre.all %}
                                        {{ genre }}
                                    {% endfor %}
                                </span>
                                </li>
                                <li >
                                <span><b>Рейтинг: </b>{{ serial }}</span>
                                </li>
                            </ul>
                        </div>
                        </div>
                    </div>
        </div>
        <div class="info">
            <h3 class="editContent"> О сериале {{ serial.title }}</h3>
            <p class="ds" >{{ serial.description }}</p>
            <p class="link"> <a target="_blank" href="{{ serial.link }}">
                Ссылка на сериал</a>
            </p>
                 {% for image in serial.cadrs_set.all %}
                     <img src="{{ image.image.url }}"  alt=""  width="350px" height="250px">
                {% endfor %}
        </div>
</body>
</html>
{% endblock %}

SemestrWork1/funCinema/templates/serials/mySerial.html
{% extends 'serials/base_form.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
</head>
<a href="{% url 'serials_list' %}">На главную страницу</a>
<body>
<table class = 'table'>
    <thead class = 'border-bottom'>
        <tr>
            <td>Название</td>
            <td>Ссылка</td>
            <td>
                <a href="{% url 'insert' %}" class="btn">
                    <i class="fas fa-plus"></i> Добавить
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for serials in list %}
            <tr>
                <td>{{ serials.title }}</td>
                <td>{{ serials.link }}</td>
                <td>
                    <a href="{% url 'update' serials.id %}" class="btn">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'delete' serials.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</body>
</html>
{% endblock  %}

SemestrWork1/funCinema/templates/serials/serials_form.html
{% extends 'serials/base_form.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{ form }}
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-success"><i class="fas fa-database"></i>Сохранить</button>
        </div>
        <div class="col">
            <a href="{% url 'list' %}" class="btn">
                <i class="fas fa-stream"></i>Вернуться
            </a>
        </div>
    </div>
</form>
{% endblock %}
</body>
</html>

SemestrWork1/funCinema/templates/serials/serials_list.html
{% extends 'serials/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fun cinema</title>
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <script src="{% static 'js/cookie.js' %}"></script>
</head>
<body>
        <div class="banner-area">
            <img src="https://img.freepik.com/free-vector/white-film-strip-background-with-text-space_1017-26105.jpg?w=2000&t=st=1671118682~exp=1671119282~hmac=e24351551145bf8275265ad1de820c10b4e63bede663666f73d96fabff3cf1e8" width="1500px" height="800px" alt="">
            <h2>Fun cinema-любимые сериалы на одном сайте</h2>
        </div>

        <div class="content-area">
            <div class="wrapper">
                <h2 class="center">О нас</h2>
                <p>
                    Всем привет! Данный сайт содержит информацию о ваших любимых сериалах в разных жанрах.
                    Вы можете прочитать информацию об актерах, рейтинге и многое другое. Этот сайт поможет вам найти не только нужный сериал,
                    но и посмотреть фавориты ваших друзей!
                    Наслаждайтесь просмотром)
                </p>
            </div>
        </div>
    </body>
</html>

</body>
</html>
{% endblock %}

SemestrWork1/funCinema/templates/serials/single_serial.html
<!DOCTYPE html>
{% extends 'serials/base.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Сериалы</title>
    <link rel="stylesheet" href="{% static 'css/serial_det.css' %}">
</head>
<body>

<div class="container" style="grid-template-columns: repeat(auto-fill,300px);margin: 150px 400px 20px 10px;">
            {%for serial in serials %}
                    <div class="item">
                    {% if serial.poster %}
                        <img src="{{ serial.poster.url }}" class="img-fluid"
                        alt="">
                    {% endif %}
                     {% if serial.title %}
                            <p>
                                <a href="{% url 'detail_serial' serial.id %}">{{ serial.title }}</a>
                            </p>
                    {% endif %}
                    </div>
            {% endfor %}
{% endblock %}
</div>
</body>
</html>

SemestrWork1/funCinema/templates/users/login.html
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/log.css' %}">

    <h2>Авторизация</h2>
    <div class="container">
    <form action="" method="POST">
      {% csrf_token %}
      <p class="form-group">
          {{ form|crispy }}
      </p>
      <div class="form-group" id="signup-button">
          <button class='custom-btn'>Войти</button>
      </div>
      <div class="form-group-text">
          <small class="text-muted ml-3" >Нет аккаунта?
              <a href="{% url 'register' %}">Зарегистрироваться</a></small>
      </div>
    </form>
    </div>
{% endblock %}

SemestrWork1/funCinema/templates/users/register.html
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/reg.css' %}">
    <h2>Регистрация</h2>
    <div class="container">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="custom-btn ">Войти</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Уже есть аккаунт? <a href="{% url 'login' %}">Авторизоваться</a></small>
      </div>
    </form>
    </div>
{% endblock %}